export default [
    "Amil",
    "Assim Saúde",
    "Bradesco Saúde",
    "Golden Cross",
    "GreenLine",
    "Hapvida",
    "Medial Saúde",
    "NotreDame Intermédica",
    "Particular",
    "Prevent Senior",
    "São Francisco Saúde",
    "SulAmerica",
    "SUS",
    "Unimed",
]