export default [
    "Clínico Geral",
    "Dermatologista",
    "Endocrinologista",
    "Fonoaudiologia",
    "Fisioterapia",
    "Gastrologista",
    "Ginecologista",
    "Infectologista",
    "Nefrologista",
    "Nutricionista",
    "Oftalmologista",
    "Odontologista",
    "Ortopedista",
    "Oncologista",
    "Otorrinolaringologista",
    "Pediatria",
    "Psiquiatria",
    "Psicólogo",
    "Quiropraxia",
    "Urologista",
]