export default [
    "Dermatologista",
    "Psiquiatra",
    "Clínico Geral",
    "Pediatra",
    "Odontologista",
    "Nutricionaista",
    "Fisioterapeuta",
    "Ginecologista",
    "Ortopedista",
    "Otorrinolaringologista",
    "Endocrinologista",
    "Oftalmologista",
    "Psicólogo",
    "Urologista",
    "Infectologista",
    "Oncologista",
    "Gastrologista",
    "Nefrologista",
]